### ISSUE TITLE
Ruby on Rails in 3 Weeks(more) - Blog - Videos 1-9 - Homework One

### ISSUE THREAD

**Issue by jendiamond** [LARailsLearners/three-in-one_blog_instruction#1]
## Go to [Ruby on Rails in 3 Weeks ](https://www.skillshare.com/classes/technology/Ruby-on-Rails-in-3-Weeks-Build-Evernote-Pinterest-and-Wordpress/1493287244)
# Do the work for 1-9 in the blog videos.

It should look like this when you are done with 1-9: (You should spell GitHub with no "a".) :+1: 

![phoebesblog](https://cloud.githubusercontent.com/assets/751697/9244027/1fa75d30-414c-11e5-92e5-a1c360de4ace.png)
### [The repository of the code](https://github.com/CrashLearner/WordpressBlogClone)

---
### The directions from the video are below.

_Remember: $ means type this command in your terminal. Don't type it in. :)_

---
#### `$ rails g controller posts`

---
#### `config/routes`

``` ruby
 resources :posts
 root "posts#index"
```

---
#### `app/controllers/post_controller.rb`

``` ruby
def index
end
```

---
#### `app/views/posts/index.html.erb`

``` ruby
<h1>index placeholder</h1>
```

---
#### `app/controller/post_controller.rb`

``` ruby
def new
end
```

---
#### `app/views/posts/new.html.erb`

``` ruby
<h1>New Post</h1>

<%= form_for :post, url: post_path do | f |
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
```

---
#### `$ rails g model Post title:string body:text`

---
#### `$ rake db:migrate`

---
#### `app/controller/post_controller.rb`

``` ruby
def create
  @post = Post.new(post_params)
  @post.save

  redirect_to @post
end

private
  def post_params
    params.require(:post).permit(:title, :body)
  end
```

---
#### `app/views/posts/show.html.erb`

``` ruby
<h1 class="title"><%= @post.title %></h1>
<p class="title">
  Submitted <%= time_ago_in_words(@post)created_at %> Ago
</p>
<p class="body">
  <%= @post.body %>
</p>
```

---
#### `app/controller/post_controller.rb`

``` ruby
def show
  @post = Post.find(params[:id])
end
```

---
#### Create a post

---
#### `app/controller/post_controller.rb`

``` ruby
def index
  @post = Post.all.order('created_at DESC')
```

---
#### `app/views/posts/index.html.erb`

``` ruby
<%= @post.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"> link_to post.title, post</h2>
  </div>
  <p class="data"><%= post.created_at.strftime("%B, %d, %y") %></p>
  </div>
<% end %>
```

---
#### `$ git checkout -b styling`

**Change:**
`app/assets/stylesheets/application.css` 
to 
`app/assets/stylesheets/application.scss`

---
#### Create file in `app/assets/stylesheets/` called:

`_normalize.scss`
#### Add to the bottom of `app/assets/stylesheets/application.css`

`````` ruby
@import 'normalize';

hint: do not delete anything on this page. THese look like comments but they are not.
````css
 *= require_tree .
 *= require_self
 */
``````
#### This is the Cascading part of CSS.

---
#### Add `app/assets/stylesheets/application.scss` add below `@import 'normalize';`

``` scss
html, body {
    font-family: 'Raleway', sans-serif;
}

h1, h2, h3, h4, h5, h6 {
    font-weight: 500;
}

a {
    text-decoration: none;
    color: inherit;
}

#sidebar {
    width: 250px;
    position: fixed;
    left: 0;
    top: 0;
    height: 100%;
    background: #f5f7f9;
    padding: 7em 0 0 0;
    border-right: 1px solid #d6dce0;
    #logo {
        width: 40px;
        position: absolute;
        right: 3em;
        top: 3em;
    }
    ul {
        list-style: none;
        text-align: right;
        padding-right: 3em;
        .category {
            font-weight: 700;
            font-size: 0.7em;
            text-transform: uppercase;
            color: #33acb7;
        }
        li {
            padding: .5em 0;
            a {
                color: #9eafba;
                text-decoration: none;
                transition: all .4s ease;
                &:hover {
                    color: #33acb7;
                }
            }
        }
        .active {
            a {
                color: #33acb7;
            }
        }
    }
    .sign_in {
        position: absolute;
        right: 3em;
        top: 80%;
        font-size: .8em;
        color: #9eafba;
    }
}

.button {
    outline: none;
    background: transparent;
    border: 1px solid #d6dce0;
    padding: .5em 1.5em;
    border-radius: 1.5em;
    &:hover {
        border: 1px solid #33acb7;
        color: #33acb7;
        a {
            color: #33acb7 !important;
        }
    }
}

.clearfix:after {
   content: ".";
   visibility: hidden;
   display: block;
   height: 0;
   clear: both;
}

#main_content {
    margin-left: 250px;
    #header {
        padding: 1em 3em;
        border-bottom: 1px solid #d6dce0;
        background: #f5f7f9;
        color: #9eafba;
        p {
            display: inline;
        }
        a {
            color: #9eafba;
            text-decoration: none;
        }
        .buttons {
            float: right;
            margin-top: -6px;
            .button {
                font-size: .8em;
                margin-left: .5em;
            }
        }
    }
    .post_wrapper {
        padding: 3em;
        border-bottom: 1px solid #d6dce0;
        .title {
            margin: 0;
            a {
                font-weight: 500;
                text-decoration: none;
                color: #2a2f35;
                font-size: 1.5em;
                &:hover {
                    color: #33acb7;
                }
            }
        }
        .date_and_author {
            color: #9eafba;
            margin: .5em 0 0 0;
        }
    }
    #post_content {
        padding: 1em 3em;
        .title {
            font-weight: 500;
            text-decoration: none;
            color: #2a2f35;
            font-size: 2.5em;
            margin-bottom: 0;
        }
        .body {
            font-size: 1.1em;
            line-height: 1.75;
        }
        .date_and_author {
            color: #9eafba;
            margin: .5em 0 2em 0;
        }
        #comments {
            h2 {
                margin: 3em 0 1em 0;
                border-bottom: 1px solid #d6dce0;
                padding-bottom: 0.5em;
            }
            h3 {
                margin-top: 2em;
            }
            .comment {
                border-bottom: 1px solid #d6dce0;
                padding: 1.5em 2em;
                .clear_both {
                    clear: both;
                }
                &:after {
                    clear: both;
                }
                .comment_content {
                    float: left;
                    .comment_name {
                        margin: 1em 0 0 0;
                        font-size: 0.7em;
                        text-transform: uppercase;
                    }
                    .comment_body {
                        font-size: 1.2em;
                        margin: 0.2em 0 0 0;
                    }
                    .comment_time {
                        margin-top: 1.2em;
                        font-size: .8em;
                    }
                }
                .button {
                    float: right;
                }
            }
            input[type="text"], textarea {
                width: 50%;
            }
        }
    }
    #page_wrapper {
        padding: 3em;
        #profile_image {
            width: 300px;
            float: left;
            margin-right: 2em;
            img {
                width: 100%;
                border-radius: 0.35em;
            }
        }
        #content {
            h1 {
                font-weight: 500;
            }
            p {
                font-size: 1.1em;
                line-height: 1.75;
            }
            a {
                color: #33acb7;
                font-weight: 700;
                text-decoration: none;
            }
        }
    }
    .links {
        margin: 2em 0;
    }
    input[type="text"], input[type="email"], input[type="password"], textarea {
        width: 90%;
        border: 1px solid #d6dce0;
        border-radius: .35em;
        margin-top: 10px;
        padding: .5em 1em;
        line-height: 1.75;
    }
    input[type="text"] {
        height: 35px;
    }
    textarea {
        min-height: 180px;
    }
    input[type="submit"] {
        outline: none;
        background: transparent;
        border: 1px solid #d6dce0;
        padding: .5em 1.5em;
        font-size: 1.1em;
        border-radius: 1.5em;
        margin-left: .5em;
        &:hover {
            border: 1px solid #33acb7;
            color: #33acb7;
        }
    }
}
```

---
#### Go to https://necolas.github.io/normalize.css/

https://github.com/CrashLearner/WordpressBlogClone/blob/master/app/assets/stylesheets/_normalize.css.scss
#### Paste this in `app/assets/stylesheets/normalize.scss` :

``` scss
/*! normalize.css v3.0.2 | MIT License | git.io/normalize */

/**
 * 1. Set default font family to sans-serif.
 * 2. Prevent iOS text size adjust after orientation change, without disabling
 *    user zoom.
 */

html {
  font-family: sans-serif; /* 1 */
  -ms-text-size-adjust: 100%; /* 2 */
  -webkit-text-size-adjust: 100%; /* 2 */
}

/**
 * Remove default margin.
 */

body {
  margin: 0;
}

/* HTML5 display definitions
   ========================================================================== */

/**
 * Correct `block` display not defined for any HTML5 element in IE 8/9.
 * Correct `block` display not defined for `details` or `summary` in IE 10/11
 * and Firefox.
 * Correct `block` display not defined for `main` in IE 11.
 */

article,
aside,
details,
figcaption,
figure,
footer,
header,
hgroup,
main,
menu,
nav,
section,
summary {
  display: block;
}

/**
 * 1. Correct `inline-block` display not defined in IE 8/9.
 * 2. Normalize vertical alignment of `progress` in Chrome, Firefox, and Opera.
 */

audio,
canvas,
progress,
video {
  display: inline-block; /* 1 */
  vertical-align: baseline; /* 2 */
}

/**
 * Prevent modern browsers from displaying `audio` without controls.
 * Remove excess height in iOS 5 devices.
 */

audio:not([controls]) {
  display: none;
  height: 0;
}

/**
 * Address `[hidden]` styling not present in IE 8/9/10.
 * Hide the `template` element in IE 8/9/11, Safari, and Firefox < 22.
 */

[hidden],
template {
  display: none;
}

/* Links
   ========================================================================== */

/**
 * Remove the gray background color from active links in IE 10.
 */

a {
  background-color: transparent;
}

/**
 * Improve readability when focused and also mouse hovered in all browsers.
 */

a:active,
a:hover {
  outline: 0;
}

/* Text-level semantics
   ========================================================================== */

/**
 * Address styling not present in IE 8/9/10/11, Safari, and Chrome.
 */

abbr[title] {
  border-bottom: 1px dotted;
}

/**
 * Address style set to `bolder` in Firefox 4+, Safari, and Chrome.
 */

b,
strong {
  font-weight: bold;
}

/**
 * Address styling not present in Safari and Chrome.
 */

dfn {
  font-style: italic;
}

/**
 * Address variable `h1` font-size and margin within `section` and `article`
 * contexts in Firefox 4+, Safari, and Chrome.
 */

h1 {
  font-size: 2em;
  margin: 0.67em 0;
}

/**
 * Address styling not present in IE 8/9.
 */

mark {
  background: #ff0;
  color: #000;
}

/**
 * Address inconsistent and variable font size in all browsers.
 */

small {
  font-size: 80%;
}

/**
 * Prevent `sub` and `sup` affecting `line-height` in all browsers.
 */

sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}

sup {
  top: -0.5em;
}

sub {
  bottom: -0.25em;
}

/* Embedded content
   ========================================================================== */

/**
 * Remove border when inside `a` element in IE 8/9/10.
 */

img {
  border: 0;
}

/**
 * Correct overflow not hidden in IE 9/10/11.
 */

svg:not(:root) {
  overflow: hidden;
}

/* Grouping content
   ========================================================================== */

/**
 * Address margin not present in IE 8/9 and Safari.
 */

figure {
  margin: 1em 40px;
}

/**
 * Address differences between Firefox and other browsers.
 */

hr {
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  height: 0;
}

/**
 * Contain overflow in all browsers.
 */

pre {
  overflow: auto;
}

/**
 * Address odd `em`-unit font size rendering in all browsers.
 */

code,
kbd,
pre,
samp {
  font-family: monospace, monospace;
  font-size: 1em;
}

/* Forms
   ========================================================================== */

/**
 * Known limitation: by default, Chrome and Safari on OS X allow very limited
 * styling of `select`, unless a `border` property is set.
 */

/**
 * 1. Correct color not being inherited.
 *    Known issue: affects color of disabled elements.
 * 2. Correct font properties not being inherited.
 * 3. Address margins set differently in Firefox 4+, Safari, and Chrome.
 */

button,
input,
optgroup,
select,
textarea {
  color: inherit; /* 1 */
  font: inherit; /* 2 */
  margin: 0; /* 3 */
}

/**
 * Address `overflow` set to `hidden` in IE 8/9/10/11.
 */

button {
  overflow: visible;
}

/**
 * Address inconsistent `text-transform` inheritance for `button` and `select`.
 * All other form control elements do not inherit `text-transform` values.
 * Correct `button` style inheritance in Firefox, IE 8/9/10/11, and Opera.
 * Correct `select` style inheritance in Firefox.
 */

button,
select {
  text-transform: none;
}

/**
 * 1. Avoid the WebKit bug in Android 4.0.* where (2) destroys native `audio`
 *    and `video` controls.
 * 2. Correct inability to style clickable `input` types in iOS.
 * 3. Improve usability and consistency of cursor style between image-type
 *    `input` and others.
 */

button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button; /* 2 */
  cursor: pointer; /* 3 */
}

/**
 * Re-set default cursor for disabled elements.
 */

button[disabled],
html input[disabled] {
  cursor: default;
}

/**
 * Remove inner padding and border in Firefox 4+.
 */

button::-moz-focus-inner,
input::-moz-focus-inner {
  border: 0;
  padding: 0;
}

/**
 * Address Firefox 4+ setting `line-height` on `input` using `!important` in
 * the UA stylesheet.
 */

input {
  line-height: normal;
}

/**
 * It's recommended that you don't attempt to style these elements.
 * Firefox's implementation doesn't respect box-sizing, padding, or width.
 *
 * 1. Address box sizing set to `content-box` in IE 8/9/10.
 * 2. Remove excess padding in IE 8/9/10.
 */

input[type="checkbox"],
input[type="radio"] {
  box-sizing: border-box; /* 1 */
  padding: 0; /* 2 */
}

/**
 * Fix the cursor style for Chrome's increment/decrement buttons. For certain
 * `font-size` values of the `input`, it causes the cursor style of the
 * decrement button to change from `default` to `text`.
 */

input[type="number"]::-webkit-inner-spin-button,
input[type="number"]::-webkit-outer-spin-button {
  height: auto;
}

/**
 * 1. Address `appearance` set to `searchfield` in Safari and Chrome.
 * 2. Address `box-sizing` set to `border-box` in Safari and Chrome
 *    (include `-moz` to future-proof).
 */

input[type="search"] {
  -webkit-appearance: textfield; /* 1 */
  -moz-box-sizing: content-box;
  -webkit-box-sizing: content-box; /* 2 */
  box-sizing: content-box;
}

/**
 * Remove inner padding and search cancel button in Safari and Chrome on OS X.
 * Safari (but not Chrome) clips the cancel button when the search input has
 * padding (and `textfield` appearance).
 */

input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
}

/**
 * Define consistent border, margin, and padding.
 */

fieldset {
  border: 1px solid #c0c0c0;
  margin: 0 2px;
  padding: 0.35em 0.625em 0.75em;
}

/**
 * 1. Correct `color` not being inherited in IE 8/9/10/11.
 * 2. Remove padding so people aren't caught out if they zero out fieldsets.
 */

legend {
  border: 0; /* 1 */
  padding: 0; /* 2 */
}

/**
 * Remove default vertical scrollbar in IE 8/9/10/11.
 */

textarea {
  overflow: auto;
}

/**
 * Don't inherit the `font-weight` (applied by a rule above).
 * NOTE: the default cannot safely be changed in Chrome and Safari on OS X.
 */

optgroup {
  font-weight: bold;
}

/* Tables
   ========================================================================== */

/**
 * Remove most spacing between table cells.
 */

table {
  border-collapse: collapse;
  border-spacing: 0;
}

td,
th {
  padding: 0;
}

-----

app/views/layouts/application.html.erb

between:
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

Add:
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>

-----

Under <body>

<div id="sidebar">
  <ul>
    <li class="category">Websites</li>
    <li><%= link_to 'Blog', root_path %></li>
  </ul>
  <ul>
    <li class="category">Social</li>
    <li><a href="https://github.com/jendiamond">Github</a></li>
    <li><a href="mailto://thejendiamond@gmail.com">Email</a></li>
    <li><a href="https://twitter.com/jendiamond">Twitter</li>
  </ul>

  <p class="sign_in">Admin Log</p>
</div>

<div id="main_content">
  <div id="header">
    <p> All Posts</p>
    <div class="buttons">
      <button class="button"><%= link_to "New Post", new_post_path %></button>
      <button class="button">Log Out</button>
    </div>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %>
  <%= yield %> 
</div>
```

---
#### `app/views/posts/new.html.erb`

``` ruby
<div id="page_wrapper">
all the code
</div>
```

---
#### `app/views/posts/sho.html.erb`

``` ruby
<div id="post_content">
all the code
</div>
```

---
## Go to [Ruby on Rails in 3 Weeks ](https://www.skillshare.com/classes/technology/Ruby-on-Rails-in-3-Weeks-Build-Evernote-Pinterest-and-Wordpress/1493287244)
# Do the work for 1-9 in the blog videos.

It should look like this when you are done with 1-9: (You should spell GitHub with no "a".)

![phoebesblog](https://cloud.githubusercontent.com/assets/751697/9244027/1fa75d30-414c-11e5-92e5-a1c360de4ace.png)
### [The repository of the code](https://github.com/CrashLearner/WordpressBlogClone)

---
### The directions from the video are below.

_Remember: $ means type this command in your terminal. Don't type it in. :)_

---
#### `$ rails g controller posts`

---
#### `config/routes`

``` ruby
 resources :posts
 root "post#index"
```

---
#### `app/controllers/post_controller.rb`

``` ruby
def index
end
```

---
#### `app/views/posts/index.html.erb`

``` ruby
<h1>index placeholder</h1>
```

---
#### `app/controller/post_controller.rb`

``` ruby
def new
end
```

---
#### `app/views/posts/new.html.erb`

``` ruby
<h1>New Post</h1>

<%= form_for :post, url: post_path do | f |
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
```

---
#### `$ rails g model Post title:string body:text`

---
#### `$ rake db:migrate`

---
#### `app/controller/post_controller.rb`

``` ruby
def create
  @post = Post.new(post_params)
  @post.save

  redirect_to @post
end

private
  def post_params
    params.require(:post).permit(:title, :body)
  end
```

---
#### `app/views/posts/show.html.erb`

``` ruby
<h1 class="title"><%= @post.title %></h1>
<p class="title">
  Submitted <%= time_ago_in_words(@post)created_at %> Ago
</p>
<p class="body">
  <%= @post.body %>
</p>
```

---
#### `app/controller/post_controller.rb`

``` ruby
def show
  @post = Post.find(params[:id])
end
```

---
#### Create a post

---
#### `app/controller/post_controller.rb`

``` ruby
def index
  @post = Post.all.order('created_at DESC')
```

---
#### `app/views/posts/index.html.erb`

``` ruby
<%= @post.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"> link_to post.title, post</h2>
  </div>
  <p class="data"><%= post.created_at.strftime("%B, %d, %y") %></p>
  </div>
<% end %>
```

---
#### `$ git checkout -b styling`

**Change:**
`app/assets/stylesheets/application.css` 
to 
`app/assets/stylesheets/application.scss`

---
#### Create file in `app/assets/stylesheets/` called:

`_normalize.scss`
#### Add to the bottom of `app/assets/stylesheets/application.css`

`````` ruby
@import 'normalize';

hint: do not delete anything on this page. THese look like comments but they are not.
````css
 *= require_tree .
 *= require_self
 */
``````
#### This is the Cascading part of CSS.

---
#### `app/views/posts/new.html.erb`

``` ruby
<div id="page_wrapper">
all the code
</div>
```

---
#### `app/views/posts/show.html.erb`

``` ruby
<div id="post_content">
all the code
</div>
```

---
